name: CI Checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: JSON Check
        run: |
          find . -name "*.json" -not -path "./node_modules/*" | xargs -n 1 npx -y jsonlint -q

      - name: HTML Check
        run: npx -y htmlhint "**/*.html"

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --base . .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
