name: CI Checks

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: JSON Check
        run: |
          find . -name "*.json" -not -path "./node_modules/*" | xargs -n 1 npx -y jsonlint -q

      - name: HTML Check
        run: npx -y htmlhint "**/*.html"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
